<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QB-CLT-1378" failures="1" tests="2" name="Verify Safety Text" time="161.529" errors="0" timestamp="2023-03-21T17:50:00 IST">
  <testcase classname="com.qburst.testing.automationcore.testng.TeslaTest" name="vefifySafteyText" time="138.31"/>
  <testcase classname="com.qburst.testing.automationcore.testng.TeslaTest" name="vefifySafteyTextFailing" time="15.318">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qburst.testing.automationcore.testng.TeslaTest.vefifySafteyTextFailing(TeslaTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- vefifySafteyTextFailing -->
</testsuite> <!-- Verify Safety Text -->
